steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-southeast2-docker.pkg.dev/$PROJECT_ID/avi-vote/avi-vote:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-southeast2-docker.pkg.dev/$PROJECT_ID/avi-vote/avi-vote:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "avi-vote",
        "--image=asia-southeast2-docker.pkg.dev/$PROJECT_ID/avi-vote/avi-vote:latest",
        "--region=asia-southeast2",
        "--platform=managed",
        "--allow-unauthenticated",
        "--quiet",
      ]
