steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/avi-vote:$COMMIT_SHA", "."]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast2"
      - "CLOUDSDK_COMPUTE_REGION=asia-southeast2"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/avi-vote:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdk/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "avi-vote",
        "--image=gcr.io/$PROJECT_ID/avi-vote:$COMMIT_SHA",
        "--region=asia-southeast2",
        "--platform=managed",
        "--allow-unauthenticated",
        "--quiet"
      ]
